import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import CategoriaClient from './CategoriaClient'

interface Props {
  params: { categoria: string }
}

const CATEGORY_SLUGS: Record<string, string> = {
  'acupuntura-uberlandia': 'Acupunturista',
  'adestrador-uberlandia': 'Adestrador de Cães',
  'advogado-uberlandia': 'Advogado',
  'aluguel-equipamentos-uberlandia': 'Aluguel de Equipamentos',
  'arquiteto-uberlandia': 'Arquiteto / Decorador de Interiores',
  'assistente-virtual-uberlandia': 'Assistente Virtual',
  'azulejista-uberlandia': 'Azulejista / Revestimento',
  'baba-uberlandia': 'Babá / Cuidador Infantil',
  'banho-tosa-uberlandia': 'Banho e Tosa',
  'bartender-uberlandia': 'Bartender / Coqueteleiro',
  'borracheiro-uberlandia': 'Borracheiro',
  'buffet-uberlandia': 'Buffet / Garçom',
  'cabeleireiro-uberlandia': 'Cabeleireiro / Barbeiro',
  'calha-rufos-uberlandia': 'Calha e Rufos',
  'carregador-uberlandia': 'Carregador / Ajudante',
  'cerimonialista-uberlandia': 'Cerimonialista',
  'chaveiro-uberlandia': 'Chaveiro',
  'chaveiro-24h-uberlandia': 'Chaveiro 24h',
  'churrasqueiro-uberlandia': 'Churrasqueiro',
  'confeitaria-uberlandia': 'Confeitaria / Doces',
  'consultor-financeiro-uberlandia': 'Consultor Financeiro',
  'contador-uberlandia': 'Contador',
  'corretor-de-imoveis-uberlandia': 'Corretor de Imóveis',
  'costureira-uberlandia': 'Costureira / Alfaiate',
  'cozinheiro-uberlandia': 'Cozinheiro(a) / Chef',
  'criador-sites-uberlandia': 'Criador de Sites / Landing Page',
  'cuidador-idosos-uberlandia': 'Cuidador de Idosos',
  'decorador-festas-uberlandia': 'Decorador de Festas',
  'dedetizacao-uberlandia': 'Dedetização',
  'dedetizacao-termitas-uberlandia': 'Dedetização de Térmitas',
  'dentista-uberlandia': 'Dentista Domiciliar',
  'desentupidor-esgoto-uberlandia': 'Desentupidor de Esgoto',
  'desentupidora-uberlandia': 'Desentupidora',
  'desenvolvedor-uberlandia': 'Desenvolvedor / Programador',
  'designer-sobrancelhas-uberlandia': 'Designer de Sobrancelhas',
  'designer-grafico-uberlandia': 'Designer Gráfico',
  'diarista-uberlandia': 'Diarista / Faxineira',
  'dj-uberlandia': 'DJ / Sonorização',
  'editor-video-uberlandia': 'Editor de Vídeo',
  'eletricista-uberlandia': 'Eletricista',
  'eletrodomesticos-uberlandia': 'Eletrodomésticos (Conserto)',
  'encanador-uberlandia': 'Encanador / Hidráulica',
  'enfermeiro-uberlandia': 'Enfermeiro(a) Domiciliar',
  'envelopamento-uberlandia': 'Envelopamento de Veículos',
  'esteticista-uberlandia': 'Esteticista / Depilação',
  'estofador-uberlandia': 'Estofador',
  'fisioterapeuta-uberlandia': 'Fisioterapeuta',
  'fonoaudiologo-uberlandia': 'Fonoaudiólogo',
  'fotografo-uberlandia': 'Fotógrafo',
  'funilaria-uberlandia': 'Funilaria e Pintura',
  'gesseiro-uberlandia': 'Gesseiro / Drywall',
  'guincho-uberlandia': 'Guincho / Reboque',
  'higienizacao-veiculos-uberlandia': 'Higienização de Veículos',
  'hotel-pets-uberlandia': 'Hotel para Pets',
  'impermeabilizacao-uberlandia': 'Impermeabilização',
  'influenciador-digital-uberlandia': 'Influenciador Digital',
  'acessorios-automotivos-uberlandia': 'Instalador de Acessórios Automotivos',
  'instalador-antenas-uberlandia': 'Instalador de Antenas',
  'cameras-cftv-uberlandia': 'Instalador de Câmeras / CFTV',
  'energia-solar-uberlandia': 'Instalador de Energia Solar',
  'grades-telas-uberlandia': 'Instalador de Grades e Telas',
  'instalador-piso-uberlandia': 'Instalador de Piso / Porcelanato',
  'som-automotivo-uberlandia': 'Instalador de Som Automotivo',
  'artes-marciais-uberlandia': 'Instrutor de Artes Marciais',
  'pilates-uberlandia': 'Instrutor de Pilates',
  'yoga-uberlandia': 'Instrutor de Yoga',
  'jardineiro-uberlandia': 'Jardineiro',
  'lavador-veiculos-uberlandia': 'Lavador de Veículos',
  'lavanderia-uberlandia': 'Lavanderia / Passadoria',
  'limpeza-caixa-dagua-uberlandia': "Limpeza de Caixa D'água",
  'limpeza-sofa-uberlandia': 'Limpeza de Sofá / Tapete',
  'locutor-uberlandia': 'Locutor',
  'manicure-uberlandia': 'Manicure / Pedicure',
  'maquiadora-uberlandia': 'Maquiadora',
  'marceneiro-uberlandia': 'Marceneiro',
  'marido-aluguel-uberlandia': 'Marido de Aluguel / Faz Tudo',
  'marmitaria-uberlandia': 'Marmitaria / Refeições',
  'marmoraria-uberlandia': 'Marmoraria',
  'martelinho-ouro-uberlandia': 'Martelinho de Ouro',
  'massagista-uberlandia': 'Massagista',
  'mecanico-uberlandia': 'Mecânico',
  'mecanico-motos-uberlandia': 'Mecânico de Motos',
  'mestre-obras-uberlandia': 'Mestre de Obras',
  'micropigmentacao-uberlandia': 'Micropigmentação',
  'montador-moveis-uberlandia': 'Montador de Móveis',
  'motorista-uberlandia': 'Motorista / Mototaxista',
  'mudanca-transporte-uberlandia': 'Mudança e Transporte',
  'nutricionista-uberlandia': 'Nutricionista',
  'nutricionista-esportivo-uberlandia': 'Nutricionista Esportivo',
  'paisagista-uberlandia': 'Paisagista',
  'pedreiro-uberlandia': 'Pedreiro / Reformas',
  'personal-stylist-uberlandia': 'Personal Stylist',
  'personal-trainer-uberlandia': 'Personal Trainer',
  'pet-sitter-uberlandia': 'Pet Sitter / Dog Walker',
  'pintor-uberlandia': 'Pintor',
  'pintura-automotiva-uberlandia': 'Pintura Automotiva',
  'pintura-fachada-uberlandia': 'Pintura de Fachada',
  'piscineiro-uberlandia': 'Piscineiro / Manutenção de Piscina',
  'podologo-uberlandia': 'Podólogo',
  'podologo-domiciliar-uberlandia': 'Podólogo Domiciliar',
  'portao-automatico-uberlandia': 'Portão Automático',
  'produtor-conteudo-uberlandia': 'Produtor de Conteúdo',
  'professor-particular-uberlandia': 'Professor Particular',
  'psicologo-uberlandia': 'Psicólogo',
  'rastreador-veicular-uberlandia': 'Rastreador Veicular',
  'seguranca-particular-uberlandia': 'Segurança Particular',
  'serralheiro-uberlandia': 'Serralheiro',
  'social-media-uberlandia': 'Social Media / Marketing',
  'soldador-uberlandia': 'Soldador',
  'tapecaria-automotiva-uberlandia': 'Tapeçaria Automotiva',
  'tatuador-uberlandia': 'Tatuador / Body Piercing',
  'ar-condicionado-uberlandia': 'Técnico de Ar Condicionado',
  'tecnico-celular-uberlandia': 'Técnico de Celular',
  'tecnico-informatica-uberlandia': 'Técnico de Informática',
  'refrigeracao-uberlandia': 'Técnico de Refrigeração',
  'tecnico-som-uberlandia': 'Técnico de Som / Imagem',
  'tecnico-eletronico-uberlandia': 'Técnico em Eletrônica',
  'telhador-uberlandia': 'Telhador / Telhadista',
  'terapeuta-uberlandia': 'Terapeuta / Reiki',
  'tradutor-uberlandia': 'Tradutor / Intérprete',
  'veterinario-uberlandia': 'Veterinário Domiciliar',
  'vidraceiro-uberlandia': 'Vidraceiro',
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const categoryName = CATEGORY_SLUGS[params.categoria]
  if (!categoryName) return { title: 'Serviços em Uberlândia | UDIHUB' }

  return {
    title: `${categoryName} em Uberlândia — Profissionais com Avaliação`,
    description: `Encontre o melhor ${categoryName} em Uberlândia, MG. Profissionais verificados, avaliações reais de clientes e contato direto pelo WhatsApp. 100% gratuito para contratar.`,
    keywords: `${categoryName} Uberlândia, ${categoryName} Uberlândia MG, contratar ${categoryName} Uberlândia, ${categoryName} perto de mim Uberlândia, melhor ${categoryName} Uberlândia`,
    openGraph: {
      title: `${categoryName} em Uberlândia | UDIHUB`,
      description: `Os melhores profissionais de ${categoryName} em Uberlândia. Avaliações reais, contato pelo WhatsApp. Grátis para contratar.`,
      url: `https://udihub.com.br/servicos/${params.categoria}`,
      siteName: 'UDIHUB',
      locale: 'pt_BR',
      type: 'website',
    },
    alternates: {
      canonical: `https://udihub.com.br/servicos/${params.categoria}`,
    },
  }
}

export default function CategoriaPage({ params }: Props) {
  return <CategoriaClient categoria={params.categoria} />
}
