export const CATEGORIES = [
  { slug: "encanador", name: "Encanador / Hidráulica", icon: "🔧" },
  { slug: "eletricista", name: "Eletricista", icon: "⚡" },
  { slug: "pintor", name: "Pintor", icon: "🎨" },
  { slug: "pedreiro", name: "Pedreiro / Reformas", icon: "🧱" },
  { slug: "ar-condicionado", name: "Técnico de Ar Condicionado", icon: "❄️" },
  { slug: "marido-aluguel", name: "Marido de Aluguel / Faz Tudo", icon: "🔨" },
  { slug: "diarista", name: "Diarista / Faxineira", icon: "🧹" },
  { slug: "jardineiro", name: "Jardineiro", icon: "🌿" },
  { slug: "montador-moveis", name: "Montador de Móveis", icon: "🪑" },
  { slug: "tecnico-informatica", name: "Técnico de Informática", icon: "💻" },
  { slug: "gesseiro", name: "Gesseiro / Drywall", icon: "🏗️" },
  { slug: "marceneiro", name: "Marceneiro", icon: "🪵" },
  { slug: "serralheiro", name: "Serralheiro", icon: "🔩" },
  { slug: "desentupidora", name: "Desentupidora", icon: "🚿" },
  { slug: "dedetizacao", name: "Dedetização", icon: "🐛" },
  { slug: "chaveiro", name: "Chaveiro", icon: "🔑" },
  { slug: "vidraceiro", name: "Vidraceiro", icon: "🪟" },
  { slug: "refrigeracao", name: "Técnico de Refrigeração", icon: "🌡️" },
  { slug: "cuidador-idosos", name: "Cuidador de Idosos", icon: "👴" },
  { slug: "baba", name: "Babá / Cuidador Infantil", icon: "👶" },
  { slug: "fotografo", name: "Fotógrafo", icon: "📸" },
  { slug: "mecanico", name: "Mecânico", icon: "🚗" },
  { slug: "pet-sitter", name: "Pet Sitter / Dog Walker", icon: "🐾" },
];

export const CITIES = [
  {
    slug: "uberlandia",
    name: "Uberlândia",
    state: "MG",
    enabled: true,
    neighborhoods: [
      "Abadia", "Aclimação", "Alto Umuarama", "Alvorada", "Arajá",
      "Aurora", "Bom Jesus", "Brasil", "Buritis", "Carajás", "Cazeca", "Centro",
      "Chácara Machado", "Chácaras Tubalina", "Cidade Jardim", "Copacabana",
      "Custódio Pereira", "Daniel Fonseca", "Dona Zulmira", "Esperança",
      "Fundinho", "Granada", "Granja Marileusa", "Guarani",
      "Ipanema", "Itamarati", "Jaraguá", "Jardim América", "Jardim Brasília",
      "Jardim Canaã", "Jardim das Palmeiras", "Jardim Europa", "Jardim Holanda",
      "Jardim Inconfidência", "Jardim Ipanema", "Jardim Karaíba", "Jardim Patrícia",
      "Jardim Sul", "Lagoinha", "Laranjeiras", "Lídice", "Luizote de Freitas",
      "Maravilha", "Marta Helena", "Martins", "Minas Gerais", "Morada da Colina",
      "Morada Nova", "Morumbi", "Nossa Senhora Aparecida", "Nova Uberlândia",
      "Osvaldo Rezende", "Pacaembu", "Pampulha", "Patrimônio", "Planalto",
      "Presidente Roosevelt", "Residencial Integração", "Rios di Itália",
      "Sabiazinho", "Santa Luzia", "Santa Maria", "Santa Mônica", "Santos Dumont",
      "São Francisco", "São Jorge", "São José", "São Lucas", "São Paulo",
      "Saraiva", "Segismundo Pereira", "Shopping Park", "Taiaman", "Tabajaras",
      "Tibery", "Tocantins", "Tubalina", "Umuarama", "Vigilato Pereira",
    ],
  },
  {
    slug: "uberaba",
    name: "Uberaba",
    state: "MG",
    enabled: false,
    neighborhoods: [
      "Abadia", "Bairro de Lourdes", "Boa Vista", "Bom Jesus", "Brasil",
      "Cajubá", "Centro", "Cidade Jardim", "Fabrício", "Gávea", "Granada",
      "Ipiranga", "Jardim América", "Jardim Califórnia", "Jardim das Acácias",
      "Jardim Finotti", "Jardim Holanda", "Lídice", "Mercês",
      "Morumbi", "Nossa Senhora Aparecida", "Nova Uberaba", "Planalto",
      "Santa Maria", "Santos Dumont", "São Benedito", "São Cristóvão",
      "Shopping Park", "Vila Brasil", "Vila Operária",
    ],
  },
  { slug: "patos-de-minas", name: "Patos de Minas", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Planalto", "Vila Nova"] },
  { slug: "ituiutaba", name: "Ituiutaba", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim Europa", "Planalto", "Vila Nova"] },
  { slug: "araguari", name: "Araguari", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Vila Nova"] },
  { slug: "frutal", name: "Frutal", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Vila Nova"] },
  { slug: "monte-carmelo", name: "Monte Carmelo", state: "MG", enabled: false, neighborhoods: ["Centro", "Vila Nova"] },
  { slug: "araxa", name: "Araxá", state: "MG", enabled: false, neighborhoods: ["Centro", "Planalto", "Vila Nova"] },
];

export const PLANS = {
  basic: {
    name: "Básico",
    price: 69,
    features: [
      "Perfil ativo e visível",
      "Aparece nas buscas",
      "Até 3 fotos",
      "Recebe leads via WhatsApp",
      "Painel de métricas",
    ],
  },
  pro: {
    name: "Pro",
    price: 99,
    features: [
      "Aparece primeiro nas buscas",
      "Badge Pro em destaque",
      "Até 10 fotos na galeria",
      "Recebe leads via WhatsApp",
      "Painel de métricas avançado",
      "Prioridade no suporte",
    ],
  },
};
