export const CATEGORIES = [
  // Construção e Reformas
  { slug: "encanador", name: "Encanador / Hidráulica", icon: "🔧" },
  { slug: "eletricista", name: "Eletricista", icon: "⚡" },
  { slug: "pintor", name: "Pintor", icon: "🎨" },
  { slug: "paisagista", name: "Paisagista", icon: "🌳" },
  { slug: "pedreiro", name: "Pedreiro / Reformas", icon: "🧱" },
  { slug: "gesseiro", name: "Gesseiro / Drywall", icon: "🏗️" },
  { slug: "marceneiro", name: "Marceneiro", icon: "🪵" },
  { slug: "serralheiro", name: "Serralheiro", icon: "🔩" },
  { slug: "vidraceiro", name: "Vidraceiro", icon: "🪟" },
  { slug: "azulejista", name: "Azulejista / Revestimento", icon: "🚧" },
  { slug: "marmoraria", name: "Marmoraria", icon: "🪨" },
  { slug: "impermeabilizacao", name: "Impermeabilização", icon: "💧" },
  { slug: "soldador", name: "Soldador", icon: "⚙️" },
  { slug: "arquiteto", name: "Arquiteto / Decorador de Interiores", icon: "🏠" },
  { slug: "artes-marciais", name: "Instrutor de Artes Marciais", icon: "🥋" },
  { slug: "portao-automatico", name: "Portão Automático", icon: "🚪" },
  { slug: "estofador", name: "Estofador", icon: "🛋️" },
  { slug: "instalador-piso", name: "Instalador de Piso / Porcelanato", icon: "🏠" },
  { slug: "energia-solar", name: "Instalador de Energia Solar", icon: "☀️" },
  { slug: "tecnico-som", name: "Técnico de Som / Imagem", icon: "🔊" },
  { slug: "telhador", name: "Telhador / Telhadista", icon: "🏠" },
  { slug: "calha-rufos", name: "Calha e Rufos", icon: "🌧️" },
  { slug: "pintura-fachada", name: "Pintura de Fachada", icon: "🖌️" },
  { slug: "grades-telas", name: "Instalador de Grades e Telas", icon: "🔒" },
  { slug: "instalador-antenas", name: "Instalador de Antenas", icon: "📡" },
  { slug: "limpeza-caixa-dagua", name: "Limpeza de Caixa D'água", icon: "💧" },
  { slug: "dedetizacao-termitas", name: "Dedetização de Térmitas", icon: "🐜" },

  // Serviços Domésticos
  { slug: "diarista", name: "Diarista / Faxineira", icon: "🧹" },
  { slug: "marido-aluguel", name: "Marido de Aluguel / Faz Tudo", icon: "🔨" },
  { slug: "ar-condicionado", name: "Técnico de Ar Condicionado", icon: "❄️" },
  { slug: "refrigeracao", name: "Técnico de Refrigeração", icon: "🌡️" },
  { slug: "eletrodomesticos", name: "Eletrodomésticos (Conserto)", icon: "🔌" },
  { slug: "montador-moveis", name: "Montador de Móveis", icon: "🪑" },
  { slug: "desentupidora", name: "Desentupidora", icon: "🚿" },
  { slug: "desentupidor-esgoto", name: "Desentupidor de Esgoto", icon: "🚰" },
  { slug: "dedetizacao", name: "Dedetização", icon: "🐛" },
  { slug: "chaveiro", name: "Chaveiro", icon: "🔑" },
  { slug: "churrasqueiro", name: "Churrasqueiro", icon: "🥩" },
  { slug: "chaveiro-24h", name: "Chaveiro 24h", icon: "🔑" },
  { slug: "jardineiro", name: "Jardineiro", icon: "🌿" },
  { slug: "piscineiro", name: "Piscineiro / Manutenção de Piscina", icon: "🏊" },
  { slug: "limpeza-sofa", name: "Limpeza de Sofá / Tapete", icon: "🧹" },
  { slug: "cameras-cftv", name: "Instalador de Câmeras / CFTV", icon: "📷" },
  { slug: "lavanderia", name: "Lavanderia / Passadoria", icon: "👕" },
  { slug: "aluguel-equipamentos", name: "Aluguel de Equipamentos", icon: "🔧" },
  { slug: "organizadora-ambientes", name: "Organizadora de Ambientes", icon: "📦" },
  { slug: "limpeza-pos-obra", name: "Limpeza Pós-Obra", icon: "🧹" },
  { slug: "automacao-residencial", name: "Automação Residencial", icon: "🏠" },

  // Tecnologia
  { slug: "tecnico-informatica", name: "Técnico de Informática", icon: "💻" },
  { slug: "tecnico-celular", name: "Técnico de Celular", icon: "📱" },
  { slug: "tecnico-eletronico", name: "Técnico em Eletrônica", icon: "📻" },
  { slug: "desenvolvedor", name: "Desenvolvedor / Programador", icon: "👨🏻‍💻" },
  { slug: "designer-grafico", name: "Designer Gráfico", icon: "🎭" },
  { slug: "social-media", name: "Social Media / Marketing", icon: "📱" },
  { slug: "editor-video", name: "Editor de Vídeo", icon: "🎬" },
  { slug: "criador-sites", name: "Criador de Sites / Landing Page", icon: "🌐" },
  { slug: "influenciador-digital", name: "Influenciador Digital", icon: "📲" },
  { slug: "produtor-conteudo", name: "Produtor de Conteúdo", icon: "🎥" },

  // Veículos
  { slug: "mecanico", name: "Mecânico", icon: "🚗" },
  { slug: "mecanico-motos", name: "Mecânico de Motos", icon: "🏍️" },
  { slug: "mestre-obras", name: "Mestre de Obras", icon: "👷" },
  { slug: "funilaria", name: "Funilaria e Pintura", icon: "🔨" },
  { slug: "martelinho-ouro", name: "Martelinho de Ouro", icon: "🔧" },
  { slug: "pintura-automotiva", name: "Pintura Automotiva", icon: "🎨" },
  { slug: "tapecaria-automotiva", name: "Tapeçaria Automotiva", icon: "🚗" },
  { slug: "som-automotivo", name: "Instalador de Som Automotivo", icon: "🎵" },
  { slug: "higienizacao-veiculos", name: "Higienização de Veículos", icon: "🧽" },
  { slug: "acessorios-automotivos", name: "Instalador de Acessórios Automotivos", icon: "⚙️" },
  { slug: "rastreador-veicular", name: "Rastreador Veicular", icon: "📡" },
  { slug: "lavador-veiculos", name: "Lavador de Veículos", icon: "🚿" },
  { slug: "envelopamento", name: "Envelopamento de Veículos", icon: "🚗" },
  { slug: "borracheiro", name: "Borracheiro", icon: "🔧" },
  { slug: "motorista", name: "Motorista / Mototaxista", icon: "🚙" },
  { slug: "mudanca-transporte", name: "Mudança e Transporte", icon: "🚚" },
  { slug: "guincho", name: "Guincho / Reboque", icon: "🚛" },
  { slug: "polimento-automotivo", name: "Polimento Automotivo", icon: "✨" },
  { slug: "despachante", name: "Despachante", icon: "📋" },

  // Saúde e Bem-Estar
  { slug: "cuidador-idosos", name: "Cuidador de Idosos", icon: "👴🏻" },
  { slug: "baba", name: "Babá / Cuidador Infantil", icon: "👩🏻‍🍼" },
  { slug: "personal-stylist", name: "Personal Stylist", icon: "👗" },
  { slug: "personal-trainer", name: "Personal Trainer", icon: "🏋🏻" },
  { slug: "pilates", name: "Instrutor de Pilates", icon: "🧘" },
  { slug: "yoga", name: "Instrutor de Yoga", icon: "🕉️" },
  { slug: "nutricionista", name: "Nutricionista", icon: "🥗" },
  { slug: "nutricionista-esportivo", name: "Nutricionista Esportivo", icon: "🥦" },
  { slug: "psicologo", name: "Psicólogo", icon: "🧠" },
  { slug: "massagista", name: "Massagista", icon: "💆🏻" },
  { slug: "fisioterapeuta", name: "Fisioterapeuta", icon: "🏥" },
  { slug: "fonoaudiologo", name: "Fonoaudiólogo", icon: "🗣️" },
  { slug: "enfermeiro", name: "Enfermeiro(a) Domiciliar", icon: "💉" },
  { slug: "terapeuta", name: "Terapeuta / Reiki", icon: "🧘🏻" },
  { slug: "dentista", name: "Dentista Domiciliar", icon: "🦷" },
  { slug: "acupuntura", name: "Acupunturista", icon: "📍" },
  { slug: "podologo-domiciliar", name: "Podólogo Domiciliar", icon: "👣" },

  // Beleza
  { slug: "cabeleireiro", name: "Cabeleireiro / Barbeiro", icon: "✂️" },
  { slug: "manicure", name: "Manicure / Pedicure", icon: "💅🏻" },
  { slug: "maquiadora", name: "Maquiadora", icon: "💄" },
  { slug: "esteticista", name: "Esteticista / Depilação", icon: "🌸" },
  { slug: "designer-sobrancelhas", name: "Designer de Sobrancelhas", icon: "👁️" },
  { slug: "micropigmentacao", name: "Micropigmentação", icon: "🖌️" },
  { slug: "tatuador", name: "Tatuador / Body Piercing", icon: "🖊️" },
  { slug: "podologo", name: "Podólogo", icon: "🦶🏻" },
  { slug: "extensao-cilios", name: "Extensão de Cílios", icon: "👁️" },
  { slug: "bronzeamento", name: "Bronzeamento", icon: "🌞" },

  // Educação
  { slug: "professor-particular", name: "Professor Particular", icon: "📚" },
  { slug: "aula-idiomas", name: "Aula de Idiomas", icon: "🌍" },
  { slug: "aula-musica", name: "Aula de Música", icon: "🎸" },
  { slug: "aula-danca", name: "Aula de Dança", icon: "💃" },

  // Alimentação
  { slug: "confeitaria", name: "Confeitaria / Doces", icon: "🎂" },
  { slug: "cozinheiro", name: "Cozinheiro(a) / Chef", icon: "👨🏻‍🍳" },
  { slug: "marmitaria", name: "Marmitaria / Refeições", icon: "🍱" },
  { slug: "bartender", name: "Bartender / Coqueteleiro", icon: "🍹" },
  { slug: "salgadeiro", name: "Salgadeiro / Quitandas", icon: "🥟" },
  { slug: "pao-artesanal", name: "Padeiro / Pão Artesanal", icon: "🍞" },
  { slug: "chocolateria", name: "Chocolateria Artesanal", icon: "🍫" },

  // Eventos
  { slug: "dj", name: "DJ / Sonorização", icon: "🎵" },
  { slug: "decorador-festas", name: "Decorador de Festas", icon: "🎉" },
  { slug: "cerimonialista", name: "Cerimonialista", icon: "💍" },
  { slug: "buffet", name: "Buffet / Garçom", icon: "🍽️" },
  { slug: "fotografo", name: "Fotógrafo", icon: "📸" },
  { slug: "locutor", name: "Locutor", icon: "🎙️" },
  { slug: "animador-festas", name: "Animador de Festas Infantis", icon: "🎪" },
  { slug: "assessor-casamentos", name: "Assessor de Casamentos", icon: "💒" },
  { slug: "videomaker", name: "Videomaker", icon: "🎬" },

  // Animais
  { slug: "pet-sitter", name: "Pet Sitter / Dog Walker", icon: "🐕‍🦺" },
  { slug: "banho-tosa", name: "Banho e Tosa", icon: "🐩" },
  { slug: "veterinario", name: "Veterinário Domiciliar", icon: "🐕" },
  { slug: "adestrador", name: "Adestrador de Cães", icon: "🐶" },
  { slug: "hotel-pets", name: "Hotel para Pets", icon: "🐾" },

  // Profissionais Liberais
  { slug: "advogado", name: "Advogado", icon: "⚖️" },
  { slug: "contador", name: "Contador", icon: "🧾" },
  { slug: "consultor-financeiro", name: "Consultor Financeiro", icon: "💰" },
  { slug: "corretor-de-imoveis", name: "Corretor de Imóveis", icon: "🏠" },
  { slug: "coach", name: "Coach / Mentor", icon: "🎯" },
  { slug: "personal-shopper", name: "Personal Shopper", icon: "🛍️" },

  // Artesanato
  { slug: "artesanato-croche", name: "Artesanato em Crochê", icon: "🧶" },
  { slug: "artesanato-trico", name: "Artesanato em Tricô", icon: "🪡" },
  { slug: "artesanato-macrame", name: "Artesanato em Macramê", icon: "🪢" },
  { slug: "artesanato-biscuit", name: "Artesanato em Biscuit", icon: "🎨" },
  { slug: "artesanato-resina", name: "Artesanato em Resina", icon: "💎" },
  { slug: "pintura-tela", name: "Pintura em Tela", icon: "🖼️" },
  { slug: "bijuteria-artesanal", name: "Bijuterias Artesanais", icon: "💍" },
  { slug: "velas-artesanais", name: "Velas e Aromaterapia", icon: "🕯️" },
  { slug: "customizacao-roupas", name: "Customização de Roupas", icon: "👕" },
  { slug: "artesanato-madeira", name: "Artesanato em Madeira", icon: "🪵" },

  // Outros
  { slug: "costureira", name: "Costureira / Alfaiate", icon: "🧵" },
  { slug: "carregador", name: "Carregador / Ajudante", icon: "🙋🏻‍♂️" },
  { slug: "seguranca-particular", name: "Segurança Particular", icon: "🛡️" },
  { slug: "tradutor", name: "Tradutor / Intérprete", icon: "🌍" },
  { slug: "assistente-virtual", name: "Assistente Virtual", icon: "💼" },
];

export const CITIES = [
  {
    slug: "uberlandia",
    name: "Uberlândia",
    state: "MG",
    enabled: true,
    neighborhoods: [
      "Abadia", "Aclimação", "Alto Umuarama", "Alvorada", "Arajá",
      "Aurora", "Bom Jesus", "Brasil", "Buritis", "Carajás", "Cazeca", "Centro",
      "Chácara Machado", "Chácaras Tubalina", "Cidade Jardim", "Copacabana",
      "Custódio Pereira", "Daniel Fonseca", "Dona Zulmira", "Esperança",
      "Fundinho", "Granada", "Granja Marileuse", "Guarani",
      "Ipanema", "Itamarati", "Jaraguá", "Jardim América", "Jardim Brasília",
      "Jardim Canaã", "Jardim das Palmeiras", "Jardim Europa", "Jardim Holanda",
      "Jardim Inconfidência", "Jardim Ipanema", "Jardim Karaíba", "Jardim Patrícia",
      "Jardim Sul", "Lagoinha", "Laranjeiras", "Lídice", "Luizote de Freitas",
      "Maravilha", "Marta Helena", "Martins", "Minas Gerais", "Morada da Colina",
      "Morada Nova", "Morumbi", "Nossa Senhora Aparecida", "Nova Uberlândia",
      "Osvaldo Rezende", "Pacaembu", "Pampulha", "Patrimônio", "Planalto",
      "Presidente Roosevelt", "Residencial Integração", "Rios di Itália",
      "Sabiazinho", "Santa Luzia", "Santa Maria", "Santa Mônica", "Santos Dumont",
      "São Francisco", "São Jorge", "São José", "São Lucas", "São Paulo",
      "Saraiva", "Segismundo Pereira", "Shopping Park", "Taiaman", "Tabajaras",
      "Tibery", "Tocantins", "Tubalina", "Umuarama", "Vigilato Pereira",
    ],
  },
  {
    slug: "uberaba",
    name: "Uberaba",
    state: "MG",
    enabled: false,
    neighborhoods: [
      "Abadia", "Bairro de Lourdes", "Boa Vista", "Bom Jesus", "Brasil",
      "Cajubá", "Centro", "Cidade Jardim", "Fabrício", "Gávea", "Granada",
      "Ipiranga", "Jardim América", "Jardim Califórnia", "Jardim das Acácias",
      "Jardim Finotti", "Jardim Holanda", "Lídice", "Mercês",
      "Morumbi", "Nossa Senhora Aparecida", "Nova Uberaba", "Planalto",
      "Santa Maria", "Santos Dumont", "São Benedito", "São Cristóvão",
      "Shopping Park", "Vila Brasil", "Vila Operária",
    ],
  },
  { slug: "patos-de-minas", name: "Patos de Minas", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Planalto", "Vila Nova"] },
  { slug: "ituiutaba", name: "Ituiutaba", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim Europa", "Planalto", "Vila Nova"] },
  { slug: "araguari", name: "Araguari", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Vila Nova"] },
  { slug: "frutal", name: "Frutal", state: "MG", enabled: false, neighborhoods: ["Centro", "Jardim América", "Vila Nova"] },
  { slug: "monte-carmelo", name: "Monte Carmelo", state: "MG", enabled: false, neighborhoods: ["Centro", "Vila Nova"] },
  { slug: "araxa", name: "Araxá", state: "MG", enabled: false, neighborhoods: ["Centro", "Planalto", "Vila Nova"] },
];

export const PLANS = {
  free: {
    name: "Gratuito",
    price: 0,
    annual: false,
    features: [
      "Perfil ativo nas buscas",
      "Até 3 fotos no perfil",
      "Até 5 clientes únicos por mês",
      "Recebe leads via WhatsApp",
    ],
  },
  professional: {
    name: "Profissional",
    price: 59.90,
    annual: false,
    features: [
      "Clientes ilimitados",
      "Aparece antes dos perfis gratuitos",
      "Até 15 fotos na galeria",
      "Selo Verificado",
      "Painel de métricas avançado",
      "Suporte prioritário",
    ],
  },
  professional_annual: {
    name: "Profissional Anual",
    price: 499.90,
    annual: true,
    features: [
      "Tudo do plano Profissional",
      "Equivalente a R$41,66/mês",
      "Destaque Premium na categoria",
      "Selo Parceiro UdiHub",
    ],
  },
  basic: {
    name: "Básico (legado)",
    price: 69,
    annual: false,
    features: ["Perfil ativo e visível", "Aparece nas buscas", "Até 3 fotos", "Recebe leads via WhatsApp"],
  },
  pro: {
    name: "Pro (legado)",
    price: 99,
    annual: false,
    features: ["Aparece primeiro nas buscas", "Badge Pro em destaque", "Até 10 fotos na galeria"],
  },
};
